### ISSUE TITLE
React input and textarea events wrong

### ISSUE THREAD

**Issue by TylerAHolden** [ionic-team/ionic-docs#1028]
https://ionicframework.com/docs/api/textarea
and 
https://ionicframework.com/docs/api/input

Nowhere in the documentation or examples does it explain that the value change event is actually onIonChange

docs say ionChange or I was assuming onChange might work but either way it's not in the example code either.

**Comment by amandaejohnston** [comment]
Thank you for the issue. This may have been added in the time since this issue was posted, but the event names are currently listed in the Events section on each component (example: https://ionicframework.com/docs/api/input#events). Due to this and the age of this issue, I'm going to go ahead and close this out, but please feel free to open a new issue if you are still having trouble.
