### ISSUE TITLE
React Quickstart: fix code sample

### ISSUE THREAD

**Issue by adamseligman** [ionic-team/ionic-docs#1097]
https://ionicframework.com/docs/react/your-first-app

Would be great to inform people to update their component include line
import { IonContent, IonHeader, IonPage, IonTitle, IonToolbar, IonList, IonItem, IonCheckbox, IonLabel, IonNote, IonBadge } from '@ionic/react';

in home.tsx

**Comment by dotNetkow** [comment]
Moved pages, I'll review this quickstart here: https://ionicframework.com/docs/react/quickstart.

**Comment by amandaejohnston** [comment]
Thank you for the issue. I'm unsure which part of the page this was originally referring to, but it looks like the docs may have been updated in the time since this issue was posted; the "your first app" page includes imports in this section https://ionicframework.com/docs/react/your-first-app#photo-gallery and the code snippets in the quickstart page all include the necessary imports as well.

Due to this and the age of the issue, I'm going to go ahead and close this out, but please feel free to open a new issue if you are still having trouble.
