### ISSUE TITLE
Desktop Browser versions not listed under "Browser Support"

### ISSUE THREAD

**Issue by tohagan** [ionic-team/ionic-docs#112]
**I'm submitting a ...**  (check one with "x")
[ ] bug report
[x] feature request

**URL:**

https://beta.ionicframework.com/docs/intro/browser-support

**Current behavior:**
- Documentation lists iOS and Android *versions* and supported desktop browser names.

**Expected behavior:**

- Fails to list the supported desktop browser *versions*.
 
**Steps to reproduce:**

**Other information:**

I suspect that this restriction will be significant because as I understand it you've stated that Ionic 4 needs CSS4 (for CSS variables) which only recent browser versions support - unless you have some other method to polyfill this.  This is a very important restriction to be aware of when selecting Ionic 3 vs 4.

**Comment by brandyscarney** [comment]
Thanks for the issue! The site has been updated since: https://ionicframework.com/docs/intro/browser-support#desktop

We don't specify the versions as it is dependent on Stencil, but there is a link at the bottom now that specifies our supported versions will always match Stencil: https://stenciljs.com/docs/browser-support/
