### ISSUE TITLE
Vue: Component template should contain exactly one root element.

### ISSUE THREAD

**Issue by iBobik** [ionic-team/ionic-docs#1159]
**URL**
https://ionicframework.com/docs/api/header (and some others)

**What is missing or inaccurate about the content on this page?**
When I copy code example for Vue as-is it will thow error "Component template should contain exactly one root element."

Ideally it would be nice to describe on docs of ion-app, ion-content, etc. how to deal with this Vue requirement because Ionic does not support having some intermediate element between app and content:
```
<ion-app>
  <div>
    <ion-header></ion-header>
    <ion-content></ion-content>
  </div>
</ion-app>
```

**Comment by brandyscarney** [comment]
Thanks for the issue! We have some docs on the structure here: https://ionicframework.com/docs/layout/structure

Since the structure page is written in vanilla JS, I think it would be good to split this into multiple framework specific pages. I'm going to close this since there's an issue to do that here: https://github.com/ionic-team/ionic-docs/issues/594
