### ISSUE TITLE
Improve contrast between text and background in docs pages

### ISSUE THREAD

**Issue by franciscovelez** [ionic-team/ionic-docs#1211]
Hi everyone,

I'm starting with Ionic and I have spent like two days reading the documentation. The thing is that I ended both days with a headache because the text color of the articles and the background has low contrast and after many hours this leads to eyestrain. If this is happening to me who don't have a visual problem, I don't want to think about the people who do.

What I would like is improve the contrast between text and background, at least the main blocks of text. 

Meanwhile, I have hacked the styles with a browser extension to set the text color as black.

Thanks a lot.

PS: Congrats for the content of the docs, It seems to me that everything is more or less clear despite all the new concepts for me that are coming up.

**Comment by amandaejohnston** [comment]
Thank you for the issue. The newer versions of the docs (Ionic v5 and above), which were created after this issue was posted, use significantly darker text. Since we aren't supporting the older versions anymore, I'm going to go ahead and close this out. Thanks again; I definitely agree this change was warranted 😄
