### ISSUE TITLE
First app using Stencil

### ISSUE THREAD

**Issue by leog** [ionic-team/ionic-docs#1314]
**Is your feature request related to a problem? Please describe.**
No.

**Describe the solution you'd like**
I was looking for a framework that could provide the best experience without any of the mainstream frameworks whatsoever, and luckily I found Ionic and its examples that work with web components directly. But it's astounding to me not to find the option to create an Ionic app using Stencil, nor finding the docs in the "First app" section to use straight up Stencil to produce top notch apps.

**Describe alternatives you've considered**
No alternative, Angular, React and soon enough Vue are covered. Not sure if there is a non-apparent reason to skip a very reasonable and usable option like Stencil.

**Additional context**
Already mentioned that my intention was to find a stripped-away form of an hybrid app without the mainstream heavy frameworks on its shoulders.

**Action points suggested**
As I'm at the time learning Stencil to be able to use it as the main driver for an hybrid app, I would like to contribute, if there is no ulterior motive not to include Stencil as an option, to the corresponding repos to make the Stencil option a reality to create the first app along with its documentation.

**Comment by rtpHarry** [comment]
There might not be much in the way of tutorials, but there is a great resource available as all of the demos in the docs are written as Stencil components:

  - https://github.com/ionic-team/docs-demo

**Comment by leog** [comment]
Thanks for pointing that out @rtpHarry. I will try to work on an official tutorial as the other frameworks and hopefully will create a PR to include it, then owners can decide whether it adds value or not, would that work?

**Comment by rtpHarry** [comment]
Well if the ionic team don't accept it I'm sure there are other sites around the web that would accept a guest post. Normally you would get sign off from somebody official on the project before working on a major feature, but that's just to stop you wasting your own time.

As far as I know, Matt Netkow is the one who has written all the current "first app" guides. Maybe he is the one to give this the nod: @dotNetkow

**Comment by leog** [comment]
Makes sense. BTW, I was thinking of basing on the [Ionic stencil conference app](https://github.com/ionic-team/ionic-stencil-conference-app).

**Comment by dotNetkow** [comment]
Hey there! Not including Stencil in the First App guide section is intentional. Feel free to create any guides and blog about it etc, but we won't be adding one to that section.

While you certainly can build hybrid mobile apps with Stencil, we're focusing on Angular and React at the moment - leveraging what the majority of web developers know, as well as what helps them get up and running quickly.

We currently recommend Stencil for building web components and design systems. 

Besides the [Stencil docs](https://stenciljs.com/docs/introduction), we recommend [Josh Morony's content and videos](https://www.joshmorony.com/topics/stencil-tutorials/), which covers all sorts of use cases. Hope that makes sense. Thank you!
