### ISSUE TITLE
Error in the name of member data

### ISSUE THREAD

**Issue by TawalMc** [ionic-team/ionic-docs#1422]
**Describe the bug**
In the get started tutorial about photo gallery (React), on the page "Taking Photos with the Camera", the name of data member is "filePath" with "P" not "filepath". When I write the code I fall on the error and when I copy also the code it is the same, so I see my debug code that something work wrong with the parameter. 

**To reproduce**
1. Go to 'https://ionicframework.com/docs/react/your-first-app/2-taking-photos'
2. Scroll down to 'https://ionicframework.com/docs/react/your-first-app/2-taking-photos#displaying-photos' and at the parth fileName
4. See error of troubleshoot "filepath" instead of "filePath"

**Expected behavior**
I think it is "filePath" not "filepath".

**Screenshots**

**Browser and OS (please complete the following information)**
 - OS: windows
 - Browser: chrome
 - Version: (Ionic cli version) 6.9.1

**Comment by amandaejohnston** [comment]
Thank you for the issue. Looking through the tutorial, all instances of the `filepath` reference currently use a lowercase "p", so that should be correct. It's possible this was fixed in the time since this issue was posted. Due to this and the age of this issue, I'm going to go ahead and close this out, but please let me know if you're still having trouble.
