### ISSUE TITLE
StarPRNT plugin does not work on iOS 13

### ISSUE THREAD

**Issue by datazen** [ionic-team/ionic-docs#1439]
**URL**
https://ionicframework.com/docs/native/star-prnt

The example is outdated and portDiscovery will not work on iOS 13.

The Ionic docs say:

```
this.starprnt.portDiscovery('all')
  .then((res: any) => console.log(res))
  .catch((error: any) => console.error(error));
```
However this does not work for me on iOS 13.  Change the function to async and works on iOS

```
async function portDiscovery() {
    try {
      let printers = await this.starprnt.portDiscovery('All');
      console.log(printers);
    } catch (e) {
      console.error(e);
    }
  }
```

**Comment by dotNetkow** [comment]
Thanks for reporting, Scott. Upon closer look, whether promise-based or async they are essentially the same, so I compared to the [repo's readme](https://github.com/auctifera-josed/starprnt#example-1) with the Ionic Native page, and I think the issue was with the portDiscovery type set to "all" instead of "All" - aka capital A letter. Could that be it?

**Comment by datazen** [comment]
Yes very possibly.  I had not noticed the case difference.   Interesting the lowercase always works on Android and the issue was only iOS.

> Thanks for reporting, Scott. Upon closer look, whether promise-based or async they are essentially the same, so I compared to the [repo's readme](https://github.com/auctifera-josed/starprnt#example-1) with the Ionic Native page, and I think the issue was with the portDiscovery type set to "all" instead of "All" - aka capital A letter. Could that be it?
