### ISSUE TITLE
[v4] document directives on components

### ISSUE THREAD

**Issue by dylanvdmerwe** [ionic-team/ionic-docs#144]
**I'm submitting a ...**  (check one with "x")
[x] bug report
[ ] feature request

**Current behavior:**
In the v4 documents, directives are not documented properly. These are currently like "secrets" that some people know and some people don't and I believe they need to be properly documented with the effect they have. 

**Expected behavior:**
Things like `tappable`, `no-bounce`, `text-center`, `padding`, etc.

**Comment by brandyscarney** [comment]
Thanks for the issue! 

- Tappable is only used internally as part of backdrop so I don't think we will be documenting it.
- No bounce has become `force-overflow="false"` and is documented in content here: https://ionicframework.com/docs/api/content#properties and in the breaking changes here: https://github.com/ionic-team/ionic/blob/master/angular/BREAKING.md#attributes-renamed-1
- All of the CSS utilities have been documented here: https://ionicframework.com/docs/layout/css-utilities

I'm going to close this since I think it's all covered now, but let me know if something's missing!
