### ISSUE TITLE
Color Generator not updating main color when replacing with a value without hashtag

### ISSUE THREAD

**Issue by noahhorlacher** [ionic-team/ionic-docs#1507]
**Describe the bug**
On the [ionic color generator page](https://ionicframework.com/docs/theming/color-generator), the corresponding '-shade' and '-tint' sub-variables don't update when replacing a hexcode in the main variable input fields with a value missing the hashtag.

**To reproduce**
1. Go to 'https://ionicframework.com/docs/theming/color-generator'
2. Click on the arrow to the right of any color input field such as 'Primary' to see the sub-variables
3. Select the current value (click on the input field and press CTRL+A) including the hashtag
4. Paste a hex code value missing the hashtag e.g. ff0000
5. The site auto-inserts the hashtag at the beginning, but doesn't auto-update the colors and values of the sub-variables, until you type in another character. It also doesn't update if it's not in focus anymore.

**Expected behavior**
After the site prepends a hashtag to the value, it's expected to auto-update the sub-variables.

**Screenshots**
![screenshot](https://user-images.githubusercontent.com/32394110/85674474-27c11800-b6c5-11ea-8a21-a6bef0ce2a25.png)

**Browser and OS**
 - OS: Ubuntu 20.04 LTS
 - Browser: Firefox, Google Chrome
 - Version: 77.0.1, 83.0.4103.116

**Comment by acran** [comment]
I tracked down the reason for this to this block:
https://github.com/ionic-team/ionic-docs/blob/bdf3a610a72783567e5c8868101dbd1bcf214176/src/components/color-gen/variable-selector/color-gen-variable-selector.tsx#L48-L51

The fix should be to simply drop the `return` since it will still ensure that the input starts with a `#` and if it not yet a valid input (i.e. 7 characters long) it will be skipped by the subsequent check anyway:
https://github.com/ionic-team/ionic-docs/blob/bdf3a610a72783567e5c8868101dbd1bcf214176/src/components/color-gen/variable-selector/color-gen-variable-selector.tsx#L58

It would also need to update `val`, too, and declaring it with `let` instead of `const`. So the fixed code would be:
~~~ts
    let val = input.value.trim();

    if (input.matches('[type="text"]') && val[0] !== '#') {
      input.value = '#' + val;
      val = input.value;
    }
~~~

**Comment by amandaejohnston** [comment]
Thank you for the issue. Taking a look at the newest version of the docs, the bug mentioned here no longer occurs -- the shade and tint colors update as expected -- but now there's a slightly different issue: the main color _doesn't_ update. It would be good if we could get these working consistently with each other.

![main color](https://i.gyazo.com/14ac0f3c64599ace2b84f17c5ff86e5b.png)
