### ISSUE TITLE
React Documentation

### ISSUE THREAD

**Issue by kayza-media** [ionic-team/ionic-docs#1683]
**URL**
https://ionicframework.com/docs/native

**What is missing or inaccurate about the content on this page?**
All the Plugin Documentations for React are linkt to the Barcode-Scanner example. https://ionicframework.com/docs/native/community#react

Please update!

**Comment by dotNetkow** [comment]
Ionic Native was originally built for Angular apps. Since then, we've expanded support for React and Vue. Unfortunately, with hundreds of plugins available and a focus on [Capacitor](https://capacitorjs.com) going forward, we won't be updating every plugin's example.

However, we provided the Barcode Scanner example for React. Conceptually, using Ionic Native with other plugins will be very similar.
