### ISSUE TITLE
Multiple React documentation issues

### ISSUE THREAD

**Issue by danderson00** [ionic-team/ionic-docs#1719]
https://ionicframework.com/docs/api/tabs

The reference on this page is just about useless. No reference is provided on using the `IonRouterOutlet` component, which is required by `IonTabs`. The `IonTab` component doesn't even seem to be used here at all? (not to mention that forcing us to use the router for tab navigation is very questionable)

It would also appear that the `IonTabs` component has been severely broken for 2 whole minor releases - https://github.com/ionic-team/ionic-framework/issues/21885

https://ionicons.com/usage

The documentation on this page is completely inaccurate for React usage. Using the `name` attribute does not seem to be supported (https://github.com/ionic-team/ionic-framework/issues/19673) - instead, users are required to import the icon and use the `icon` attribute. *This is fine, but the documentation does not specify this.* 

Can you imagine how many collective hours of your customers' time you have wasted, just with these two issues alone? I can't wait to find more ways in which my time is wasted! Please, please, please fix these to avoid alienating us further! I apologise for the harsh tone, but I'm a little frustrated with the Ionic Framework right now.

**Comment by danderson00** [comment]
https://ionicframework.com/docs/api/header

Some documentation on styling the header (and other components) would be very useful, similar to how material-ui [shows relevant CSS classes](https://material-ui.com/api/toolbar/#css).

For example, how does one remove the solid line (or modify the color, etc) underneath IonHeader?

**Comment by danderson00** [comment]
https://ionicframework.com/docs/api/card

Here's another suggestion - make the example code in the `Usage` section match the rendered example. I am aware that the `View Source` link underneath the rendered example opens plain Javascript version of the example on github, but React syntax can differ significantly enough in some cases that the plain Javascript version can be misleading.

**Comment by danderson00** [comment]
My frustration has subsided after being able to produce something decent over a long couple of days. 

I apologise again for the harsh tone, no one wants that kind of feedback. Ionic is a great product when you consider the whole stack. Please, please, please improve the reference docs - perhaps using vuetifyjs.com or material-ui.com as a source of inspiration (they are not perfect but the rich set of examples on both sites are excellent).

**Comment by brandyscarney** [comment]
Hello! Thank you for your feedback. We have updated the documentation since this issue was created to include runnable playground demos on all of the component pages that open in StackBlitz for each framework. The tabs documentation includes an example of [usage with router](https://ionicframework.com/docs/api/tabs#usage-with-router) and links to a guide on [navigation with tabs](https://ionicframework.com/docs/react/navigation#working-with-tabs).

> Here's another suggestion - make the example code in the Usage section match the rendered example.

The demos on each component now match the usage, see [Card](https://ionicframework.com/docs/api/card#basic-usage). 

I am going to close this issue as I believe all of your feedback has since been addressed, but please feel free to open a new issue if there is anything else we could improve.
