### ISSUE TITLE
ion-page missing from index

### ISSUE THREAD

**Issue by cfjedimaster** [ionic-team/ionic-docs#1785]
**URL**
https://ionicframework.com/docs/api

**What is missing or inaccurate about the content on this page?**
There is no documentation for `ion-page`.

**Comment by liamdebeasi** [comment]
Thanks! IonPage is a framework-specific component that only applies to routing and only appears in React and Vue, which is why the component does not appear in the API docs there.

I added documentation for Vue and React.

Vue: https://ionicframework.com/docs/vue/navigation#ionpage
React: https://ionicframework.com/docs/react/navigation#ionpage
