### ISSUE TITLE
Example for custom page transition.

### ISSUE THREAD

**Issue by y0nd0** [ionic-team/ionic-docs#1833]
Please add an example for custom page transition.
https://ionicframework.com/docs/api/router-outlet

| animation | |
|--- | ---|
| Description | By default `ion-nav` animates transition between pages based in the mode (ios or material design). However, this property allows to create custom transition using `AnimateBuilder` functions.|
| Type | ((baseEl: any, opts?: any) => Animation) | undefined |

I cannot bring it to life. I searched the whole web. Every single website. Line for line.

**Comment by Agular** [comment]
Try looking at the Ionic 5 animation documentation https://ionicframework.com/docs/utilities/animations
Although it missing too a bit since e.g. for modals, when querying for backdrop or wrapper element, it should be queried from the shadow dom using shadowRoot e.g. baseEl.shadowRoot.querySelector('ion-backdrop')

Maybe this helps

**Comment by amandaejohnston** [comment]
Thank you for the issue. I'm going to merge this with this similar issue: https://github.com/ionic-team/ionic-docs/issues/1492 While it specifically mentions `ion-nav`, the general idea is the same, and I'm sure there are other places we should link to the animation docs from.
