### ISSUE TITLE
How about some VueJS + TS Examples

### ISSUE THREAD

**Issue by barcovanrhijn** [ionic-team/ionic-docs#1844]
**Is your feature request related to a problem? Please describe.**
I noticed from the Forums that it's a known issue that VueJS devs are not always used to TS. The Ionic docs don't currently feature VueJS examples. This is especially important with Capacitor and Cordova plugin use. 

**Describe the solution you'd like**
It would be great if there are a few VueJs examples in the Ionic Docs. Even if you link to one generic example it would help greatly. There's nothing worse than debugging TS issues for a day after using working JS in a VueJs project.

**Describe alternatives you've considered**
I've searched online but most of the Vuejs + Ionic related blogs online are outdated. At the moment I'm just reading plugin code. It gets me fairly close but the examples everywhere in Ionic are not valid for TS. Weird that Ionic only forces VueJS developers into TS.

**Comment by amandaejohnston** [comment]
Thank you for the issue. In the time since this was posted, we've added live demos to component docs pages with example code in all supported frameworks, including Vue. Type information has been included where relevant. Here's an example: https://ionicframework.com/docs/api/modal#inline-modals-recommended I'm going to close this out.
