### ISSUE TITLE
[ion-badge-react] slot prop is missing

### ISSUE THREAD

**Issue by avalanche1** [ionic-team/ionic-docs#1918]
**URL**
https://ionicframework.com/docs/api/badge

**What is missing or inaccurate about the content on this page?**
`slot` prop is not documented

**Comment by liamdebeasi** [comment]
Thanks for the issue. `ion-badge` does not have any slots which is why slots do not show up on that page. I am assuming you are using a badge inside of `ion-item`, in which case the slots are documented on the page for `ion-item`: https://ionicframework.com/docs/api/item

When you write the following:

```html
<ion-item>
  <ion-badge slot="start">...</ion-badge>
</ion-item>
```

You are essentially saying "Place the badge inside of the 'start' slot for the item". In other words, the slot is part of the item, not the badge.
