### ISSUE TITLE
Javascript and Angular gesture animation docs issues

### ISSUE THREAD

**Issue by dexster** [ionic-team/ionic-docs#1930]
**URL**
https://ionicframework.com/docs/utilities/animations#gesture-animations

**What is missing or inaccurate about the content on this page?**

### First issue

Current doc for Javascript and Angular tabs
```
const gesture = createGesture({
  el: square,
  threshold: 0,
  gestureName: 'square-drag',
  onMove: ev: onMove(ev),
  onEnd: ev: onEnd(ev)
})
```

onMove and onEnd should look like this
``` 
  onMove: ev => onMove(ev),
  onEnd: ev => onEnd(ev)
```

### Second issue in the same code snippet

```
const onMove = (ev): {
  if (!started) {
    animation.progressStart();
    started = true;
  }

  animation.progressStep(getStep(ev));
}
```

`progressStart()` requires a bool argument

### Third issue in the same code snippet

The onEnd method for Javascript and Angular
```
const onEnd = (ev): {
  if (!started) { return; }

  gesture.enable(false);

  const step = getStep(ev);
  const shouldComplete = step > 0.5;

  animation
    .progressEnd((shouldComplete) ? 1 : 0, step)
    .onFinish((): { gesture.enable(true); });

  initialStep = (shouldComplete) ? MAX_TRANSLATE : 0;
  started = false;
}
```

This is incorrect because the progressEnd typescript definition returns void so you cannot chain onFinish()
`progressEnd(playTo: 0 | 1 | undefined, step: number, dur?: number): void;`

Secondly, onFinish should look like this
` .onFinish(() => { gesture.enable(true); });`

**Comment by liamdebeasi** [comment]
Thanks! I resolved these issues and published updates to the docs.

First Issue: This was fixed in https://github.com/ionic-team/ionic-docs/pull/1992 and https://github.com/ionic-team/ionic-docs/pull/1993.

Second Issue: The usage example is correct, but the interface on the docs is misleading. The first parameter in `progressStart` defaults to `false` if not passed in. This was fixed in https://github.com/ionic-team/ionic-docs/pull/1994 and https://github.com/ionic-team/ionic-docs/pull/1995.

Third Issue: The usage example is correct, but the actual TypeScript interface exported from Ionic Framework is wrong. This was fixed in https://github.com/ionic-team/ionic-framework/pull/23536 and will be available in an upcoming release of Ionic Framework.

The docs updates were just published, so you should see them in about 20 minutes (might need a hard refresh after that). Thanks for reporting this!
