### ISSUE TITLE
Missing or difficult to find controller documentation

### ISSUE THREAD

**Issue by claytongulick** [ionic-team/ionic-docs#1954]
Since the change away from the custom elements approach to the controllers, like modal-controller, popover-controller, etc... the documentation on how to use the controllers is very difficult to find, or missing.

It used to be available on the main components documentation page, but now I can't find it even when searching directly for the class name.

The only place where they are mentioned that I can find is the breaking change log.

I'm using vanilla JS, so import the controller classes directly from core.

Thanks!!

**Comment by amandaejohnston** [comment]
Thank you for the issue. We've since added live demo examples for how to present overlays using their respective controllers: https://ionicframework.com/docs/api/modal#controller-modals 

It's also worth noting that some overlays (with more to come in the upcoming v7 release) have inline usage patterns available instead, which we would actually recommend over using the controller where it makes sense. Here's an example: https://ionicframework.com/docs/api/modal#inline-modals-recommended

Closing this out.
