### ISSUE TITLE
Ion Item - Slot\s

### ISSUE THREAD

**Issue by avalanche1** [ionic-team/ionic-docs#1956]
**URL**
https://ionicframework.com/docs/api/item-option#slots

**What is missing or inaccurate about the content on this page?**
<IonItemOption> doesn't have a prop `slots`. But it reads like it has, from the docs.
'Slots' header sd be changed to 'Slot'; and mentioned that it is not a prop on `IonItemOption`, but on it's content, like `IonIcon`.

**Comment by amandaejohnston** [comment]
Thank you for the issue. Slots aren't a component property; rather, they're a feature of web components in general: https://developer.mozilla.org/en-US/docs/Web/Web_Components/Using_templates_and_slots Child components can be placed into the slots of the `IonItemOption` to position them in certain ways. Due to this and the age of this issue, I'm going to close this out, but please feel free to open a new issue if you're still having trouble.
