### ISSUE TITLE
Angular - Step 3 Saving Photos: CameraPhoto type is deprecated

### ISSUE THREAD

**Issue by magz99** [ionic-team/ionic-docs#2031]
**URL**
https://ionicframework.com/docs/angular/your-first-app/3-saving-photos#filesystem-api

**What is missing or inaccurate about the content on this page?**
The first code snippet example under the "Filesystem API" section is using a deprecated type:

`private async savePicture(cameraPhoto: CameraPhoto) { }`

The `CameraPhoto` type is deprecated and the example could be updated to use `Photo` instead

**Comment by brinehart** [comment]
What do you all think is the best term since the documentation is using the interface name `Photo` elsewhere in the example. This can be confusing since Capacitor uses both `Photo` and `CameraPhoto`

There are a few different synonyms that could be used to avoid this confusion:
`Picture`,
`Snap`,
`Shot`,
`CameraPicture`

Just a few that come to the top of my head. What does everyone think?

**Comment by jcesarmobile** [comment]
thanks for the issue, it's fixed now
