### ISSUE TITLE
Document usage pattern for error slot with ion-item in React/Vue/Vanilla

### ISSUE THREAD

**Issue by sean-perkins** [ionic-team/ionic-docs#2186]
**URL**
https://ionicframework.com/docs/api/item

**What is missing or inaccurate about the content on this page?**

The usage of `ion-item` does not mention that implementers in environments other than Angular, will need to manually add the `ion-invalid` class to the `ion-item` element, to make the error slot visible to the user. 

Without this information, it's confusing to implementers and appears as a bug when the error slot is not presented.

**Comment by vandor** [comment]
This is a source of confusion for me, too. I'm using the Vue bindings and had to dig into the source code for `ion-item` to figure out why it wasn't displaying the `error` slot content.

In case it's helpful to note, something that complicated this troubleshooting for me was that using the slot attribute (web component-style) felt unusual in my vue template (and furthermore my IDE gave a warning about the slot attribute being deprecated), so that made me think that the docs were outdated or perhaps hadn't been updated to be accurate for Vue. I spent some time fruitlessly trying variations of `<template #error><ion-note>My error message</ion-note</template>`.

So it would be helpful if the docs for `ion-item` had a note that the slot attribute is a valid web component-style slot.

**Comment by brandyscarney** [comment]
Can this be closed? I added it in the Helper & Error text section here with example of adding it in the code: https://ionicframework.com/docs/api/item#helper--error-text

**Comment by amandaejohnston** [comment]
Closing this out as it's since been added per the above comment.
