### ISSUE TITLE
ion-datetime modal have a problem

### ISSUE THREAD

**Issue by lixian1998** [ionic-team/ionic-docs#2214]
https://user-images.githubusercontent.com/73985389/156731004-bebb3846-d71c-4e5d-8728-b0120454fe93.mp4

**Comment by lixian1998** [comment]
I recorded a video and need to download it to watch, this is what I found when using ion-datetime, I think the previous ion-datetime is better

**Comment by amandaejohnston** [comment]
Thank you for the issue. We've since overhauled the datetime page with newer demo examples: https://ionicframework.com/docs/api/datetime We also have the new `ion-datetime-button` component, which can be used to open a datetime in a modal with a cleaner user experience: https://ionicframework.com/docs/api/datetime-button

If this is still a problem you're encountering, please file a new issue on the Ionic Framework repo and include a minimal reproduction: https://github.com/ionic-team/ionic-framework/issues/new/choose Thank you.
