### ISSUE TITLE
Usages and readme property missing from @ionic/docs/core.json  v6.1.3

### ISSUE THREAD

**Issue by sandeeppatidar30** [ionic-team/ionic-docs#2392]
**Describe the bug**
@ionic/docs/core.json does not have readme property for component and it has empty object for usages property.

**To reproduce**
1. Visit https://unpkg.com/@ionic/docs@6.1.10/core.json, where it is missing
2. Visit https://unpkg.com/@ionic/docs@6.1.2/core.json, readme and usage properties there with correct values

**Expected behavior**
It should generate core.json with readme and usage properties.

**Screenshots**
No

**Browser and OS (please complete the following information)**
 - OS: [e.g. iOS]: Windows
 - Browser: [e.g. chrome, safari] Chorme
 - Version: [e.g. 22] v6.1.10

**Additional context**
No

**Comment by sean-perkins** [comment]
@sandeeppatidar30 since we have migrated our docs from `ionic-framework` to `ionic-docs`, we no longer have readme files that get compiled into the `core.json` file. That file was intended for internal use in our build processes. 

Can you explain why you need this information?

**Comment by sandeeppatidar30** [comment]
@sean-perkins , We are styling ionic components as per our custom style guide and we want to keep ionic components' README.md file with those styled components' README.md files, so all documentation related to a component can be found in one file only. But @ionic/core does not include README.md file in final distribution so we are featching all info from @ionic/docs/core.json and creating ionic readme.md again at our end.

**Comment by sean-perkins** [comment]
@sandeeppatidar30 we no longer generate README files in that format anymore. You could generate the files yourself using a similar script to: https://github.com/ionic-team/ionic-docs/blob/main/scripts/api.js which takes the contents of `core.json` and generates markdown content. You will just want to generate the contents as a single file per component, instead of how we generate a separate file for slots/props/etc.
