### ISSUE TITLE
Alert/Loading controller links are broken. 

### ISSUE THREAD

**Issue by bensperry** [ionic-team/ionic-docs#254]
To repro: click “Alert Controller” or “Loading Controller” in the alert and loading docs:

https://beta.ionicframework.com/docs/api/loading
https://beta.ionicframework.com/docs/api/alert/alert-controller

**Comment by camwiegert** [comment]
The issue here is that the client-side router doesn't enforce trailing slashes like the server does, so relatives links resolve differently depending on how you get to the page.

Changing that relative link to an absolute URL would solve the problem (but break it in the core repo markdown). I think we ought to add the ability for stencil-router to enforce trailing slashes or no trailing slashes.

**Comment by rtpHarry** [comment]
This problem is actually a lot worse than this, I created a PR for it but it's not got any love yet:

https://github.com/ionic-team/ionic/pull/17256
