### ISSUE TITLE
v4 Docs: Ion-Avatar image missing

### ISSUE THREAD

**Issue by chrisgriffith** [ionic-team/ionic-docs#262]
**I'm submitting a ...**  (check one with "x")
[X ] bug report
[ ] feature request

**URL:**
https://beta.ionicframework.com/docs/api/avatar

**Current behavior:**
the images within the avatars are missing

**Expected behavior:**
Show the images.

**Steps to reproduce:**

**Other information:**

**Comment by RafaelKr** [comment]
Also some styles aren't loading correctly with the error:
`Refused to apply style from 'https://beta.ionicframework.com/css/ionic.bundle.css' because its MIME type ('text/html') is not a supported stylesheet MIME type, and strict MIME checking is enabled.`

Maybe this is just a webserver misconfiguration?

When you want to load the avatar source file, you get the Ionic Docs Main HTML back currently: https://beta.ionicframework.com/src/components/avatar/test/avatar.svg

**Comment by camwiegert** [comment]
Appears this is no longer an issue.
