### ISSUE TITLE
content: Stencil code examples

### ISSUE THREAD

**Issue by miqmago** [ionic-team/ionic-docs#2632]
### URL

https://ionicframework.com/docs/api/modal#controller-modals

### Issue Description

Missing Stencil code examples which was present on v5.
Do you plan to add them in near future?

**Comment by sean-perkins** [comment]
We currently do not have plans to re-add the Stencil code usage examples for each component. With component playgrounds we are focusing on framework integrations (Angular/React/Vue) and Javascript for other use cases (e.g. Stencil). 

Since all Ionic components are web components, usage in an HTML environment or Stencil should be very similar. Developers can additionally reference the React usage examples if they are unfamiliar with JSX binding syntax.

**Comment by sean-perkins** [comment]
@miqmago great question!

Stencil is still very much a priority of Ionic and has an active and growing team focused on enhancing the web component compiler. Ionic Framework is built entirely with Stencil, so Stencil isn't going anywhere 🙂 

Originally Stencil had a very wide scope of packages, some experimental, to help Stencil be used in a variety of development scenarios. As time progressed, these packages were not given the time and attention they required and became stale. To enhance the quality of these packages, we have moved some packages to the community, so that the open source community using those packages can help champion maintaining those integrations. This allows the Stencil team to continue to focus on the active development of Stencil, as well as the priority packages that we still maintain in the Ionic org. 

Stencil can still be used as a potential substitute for Angular/React/etc., but our recommendation is using Stencil for building your design system and components. You can then optionally choose if you want to use a framework or continue to use Stencil for your other needs. 

If there are any Ionic Framework components that you have an issue using in your Stencil library/app, please open an issue and we would be more than happy to help!

**Comment by miqmago** [comment]
Thanks @sean-perkins, I understand that for an experienced programmer, with javascript and React examples one can deduce how to make it to work in Stencil, but anyway, I hope that some day the examples and code snippets for Stencil will be included again in the Ionic Framework page, they where really useful and a great help for those who are developing web components based on Ionic components in Stencil 🙏 

I would like to ask a related question to the community packages you mentioned: a small team of us we've developed a [forms-reactive](https://www.npmjs.com/package/forms-reactive) component entirely in Stencil. This is a port from Angular Reactive Forms so it can be used in any javascript framework or none at all. It works really fine. It is also addapted to work with almost all ion-?? input/radio/select... but there is still place for improvement and we do not have much time to maintain, although we do some improvements time to time. I don't know if there is something we could to to let the community know about it, so it can be propelled to the next galaxy :)

@rwaskiewicz suggested about [proposing a package](https://github.com/stencil-community/proposals) but it's not really a proposal as it is already developed... Would be really pleased if you could address me to the right place or if you let me know your thoughts.
