### ISSUE TITLE
content: recommend fork of file-opener2

### ISSUE THREAD

**Issue by arnotixe** [ionic-team/ionic-docs#2662]
### URL

https://ionicframework.com/docs/native/file-opener

### Issue Description

I'd like to suggest changing the file-opener2 plugin recommended on https://ionicframework.com/docs/native/file-opener to https://github.com/capacitor-community/file-opener instead. 

The maintainer of file-opener2 seems unresponsive last 2 years. There are working (critical) PRs available but nothing happens. So, someone (ryaa) forked it and it works as intended on android and iOS.

I do not know enough about the cordova vs capacitor part to tell if the fork has anything to do with cordova though.

The recommended file-opener2 plugin causes Google Play store rejects since it pulls in an unwanted permission, REQUEST_INSTALL_PACKAGES. The fork does not.

**Comment by arnotixe** [comment]
For reference, on the referred (stale) project, this is the most critical bug and fix: https://github.com/pwlin/cordova-plugin-file-opener2/issues/329

**Comment by jcesarmobile** [comment]
The Ionic website has been updated to show Capacitor plugins that Ionic owns instead of 3rd party plugins, so any third party Cordova plugin has been removed.

Anyway, the docs were generated from awesome-cordova-plugins repository, you should report the issue there https://github.com/danielsogl/awesome-cordova-plugins
