### ISSUE TITLE
content: ionic v6 android permission 

### ISSUE THREAD

**Issue by swapnaliDeveloper** [ionic-team/ionic-docs#2690]
### URL

https://ionicframework.com/docs/native/android-permissions

### Issue Description

Page not found - https://ionicframework.com/docs/native/android-permissions

**Comment by jcesarmobile** [comment]
The Ionic website has been updated to show Capacitor plugins that Ionic owns instead of 3rd party plugins, so any third party Cordova plugin has been removed.

Since the docs were generated from awesome-cordova-plugins repository, I've created an issue there so they are aware that they need documentation:

https://github.com/danielsogl/awesome-cordova-plugins/issues/4487
