### ISSUE TITLE
bug: colors properties in ion-toolbar are incorrect

### ISSUE THREAD

**Issue by ColeJJ** [ionic-team/ionic-docs#2757]
### Describe the Bug

see: https://stackblitz.com/run?file=src%2Fapp%2Fexample.component.html

The colors of the toolbars are not correct.
Example: `color="dark"` somehow got a light grey-looking color

### Expected Behavior

With `color="dark"` I would expect to get the color depicted in "light color".

### Steps to Reproduce

Just have a look at the stackblitz example of the website itself.
https://ionicframework.com/docs/api/toolbar -> Theming

### Screenshots

![image](https://user-images.githubusercontent.com/50582353/216641629-f8331c7c-5643-4b0c-b6b0-33b3909d08d8.png)

### Operating System

MacOS

### Browser

Google Chrome

### Version

109.0.5414.119

**Comment by amandaejohnston** [comment]
Thank you for the issue. The toolbars are behaving as expected; the color difference is because you have Stackblitz running in dark mode, which changes the default colors in Ionic to better align with the dark background. If you change the docs site to dark mode by clicking the moon button at the right of the toolbar, you'll see the same colors in the demo:

![dark mode toolbars](https://i.gyazo.com/f40d85fefdcc3e4cf308fbdb5cc0b8ce.png)

Does this resolve your concern?
