### ISSUE TITLE
content: Vu3 Modal: this.$refs.modal: Object is of type 'unknown'.

### ISSUE THREAD

**Issue by acarlstein** [ionic-team/ionic-docs#2786]
### URL

https://ionicframework.com/docs/api/modal

### Issue Description

Language: Typescript
NPM Version: 9.4.1
Node Version: v16.15.1
Ionic Version: 6.20.8

In the example provided on the page, these lines below fail:

* `this.$refs.modal.$el.dismiss(null, 'cancel');`
* `this.$refs.modal.$el.dismiss(name, 'confirm');`

And the error that shows on `this.$refs.modal` is **_Object is of type 'unknown'_**.

Plus, I had to change this:
```typescript
onWillDismiss(ev: CustomEvent<OverlayEventDetail>) {
        if (ev.detail.role === 'confirm') {
          this.message = `Hello, ${ev.detail.data}!`;
        }
},
```

to this:
```typescript
onWillDismiss(ev: any) {
      if (ev.detail.role === 'confirm') {
        this.message = `Hello, ${ev.detail.data}!`;
      }
},
```
because `OverlayEventDetail` gives **_Cannot find name 'OverlayEventDetail'_**

I tried to use `(this.$refs.modal as HTMLIonModalElement).dismiss();` but I get **_'HTMLIonModalElement' is not defined_**. When I try to import `HTMLIonModalElement`, I can't find the plugin that I should import to have it.

So, it makes me wonder if, by any chance, the documentation might me outdated or there is a configuration missing that I should be aware.

Thank you for your time. Much appreciated.

**Comment by amandaejohnston** [comment]
Thank you for the issue. Are you referring to the "Inline Modals" demo here? https://ionicframework.com/docs/api/modal#inline-modals-recommended If so, I'm unable to replicate the errors, either when running the demo in Stackblitz (which you can do by clicking the ⚡ button at the top right of the demo) or after downloading the Stackblitz code as a repo and running it locally. (Link: https://github.com/amandaejohnston/angular-s25hzq)

I can say that `OverlayEventDetail` is imported in this line from the example:
```js
import { OverlayEventDetail } from '@ionic/core/components';
```
As for the others, I'm not sure. `HTMLIonModalElement` is a type that should be included when Ionic is installed. Could you post a link to a Github repo I could use to replicate these errors?

**Comment by acarlstein** [comment]
@amandaejohnston Thank you for answering to my issue, much appreciated.

Sorry if I didn't express myself correctly, I will try to do better. 
Also, I found other issues as we speak that I want to share.

1) Yes. I'm trying to do an _Inline Modal_ but using _Vue3_ instead of _Vue2_. I found out that the example works for _Vue2_ but fails to work with _Vue3_, since _Vue3_ focus on _Composition API_, while _Vue2_ use _Option API_.

2) The `modalController` fails to recognize the _Inline Modal_. So, when I use it, it creates an empty Modal instead controlling the existent one. However, if you can provide an example of an _Inline Modal_ being controlled by `modalController` in Vue3, I would be very grateful since I spend hours trying to make it work unsuccessful.

3) I'm trying to open the modal programmatically, by receiving an event, instead of pressing a button (like the example provided). However, as I pointed on my second bullet, `modalController` doesn't have an `open` method, only `create` method, which fails to recognize the _Inline Modal_.

4) Thank you for providing the line below. I confess that I missed it. I will try it out.
```typescript
import { OverlayEventDetail } from '@ionic/core/components';
```` 

5) I can't provide you with a link to the GitHub since the repository isn't public. However, if you wish to replicate it, you only need to use Typescript instead of JavaScript, and use Vue3 instead of Vue2. 

6) While I understand that `HTMLIonModalElement`, if you can provide me with information of where is it, then I can try to figure out the rest by muself.

**Comment by amandaejohnston** [comment]
It looks like you've already posted another issue regarding `modalController` here: https://github.com/ionic-team/ionic-docs/issues/2790 I'll address that part over there, so we can use this issue to focus on the errors from your original post.

For the `this.$refs.modal` error, I will need a minimal reproduction in order to debug what the problem could be. It will also be used to ensure the bug is fixed down the line. You can create a separate repo that only contains the code needed to reproduce the error and post a link to that. More information: https://ionicframework.com/docs/contributing/how-to-contribute#creating-a-good-code-reproduction

`HTMLIonModalElement` isn't exported in the traditional sense, so it isn't meant to be imported directly. It is included in the Ionic package's type declarations file, so when you install `@ionic/vue`, Typescript should automatically detect the type and allow you to use it. I'm able to do so without importing it in an Ionic Vue test project I've created locally, which has the same ESLint rules as your example snippet. It would be helpful if you could also ensure the error with `HTMLIonModalElement` triggers in your minimal reproduction.
