### ISSUE TITLE
content: where to find icon custom SVG usage isn't obvious

### ISSUE THREAD

**Issue by JacobHornbeck** [ionic-team/ionic-docs#2813]
### URL

https://ionicframework.com/docs/api/icon

### Issue Description

In the documentation on [ionicframework.com](https://ionicframework.com/docs/api/icon), we read the following:

> Icon is a simple component made available through the [Ionicons](https://ionic.io/ionicons) library, which comes pre-packaged by default with all Ionic Framework applications. ***It can be used to display any icon from the Ionicons set, or a custom SVG.*** It also has support for styling such as size and color.

It says that we can use the `<ion-icon>` tag for a custom SVG, but does not say how we can do that. The only examples given are for the icons in the Ionicons set.

Someone who knows how this is done, please let me know how it is done, and update the docs so others can know how to do it as well.

**Comment by JacobHornbeck** [comment]
@amandaejohnston Thank you for that. I actually had ended up finding that on my own, looking for something else.
I do think that a simplified version of the [ionic.io](https://ionic.io/ionicons/usage) `<ion-icon>` docs should be put in the [Ionicframework.com](https://ionicframework.com/docs/api/icon) `<ion-icon>` docs. A link would help, but if a simplified version was in it, and then have a link to the more details one, would be even better.

**Comment by amandaejohnston** [comment]
We're intentionally trying to leave as much of the heavy lifting to the main Ionicons site as possible to make it clear that Ionic Framework is not required to use Ionicons. The Framework docs site has the live demos that combine the two, but otherwise we want to leave most of the usage examples on the Ionicons site.

That said, I've made where to find said usage examples more obvious in https://github.com/ionic-team/ionic-docs/pull/2816 and have closed this out. Thanks again!
