### ISSUE TITLE
bug: starting a search with shortcut (⌘ + K) does not initiate with the input focused

### ISSUE THREAD

**Issue by izyumidev** [ionic-team/ionic-docs#2885]
### Describe the Bug

On any page of the docs, pressing ⌘ + K starts a search, but the input field is not focused, and it's not even the first thing I can access using tab, requiring me to click the search bar.

### Expected Behavior

When I press ⌘ + K, the search modal should open with the input field focused.

### Steps to Reproduce

Go to any page of the docs where the search bar is visible at the navigation and press the shortcut noted in the search bar. The search modal would show up, but the input field is not focused.

### Screenshots

<img width="505" alt="Screenshot20230406111130@2x" src="https://user-images.githubusercontent.com/36561306/230422138-7fd9514d-075e-4621-bb4d-f5a41c13f8f8.png">

### Operating System

Mac

### Browser

I was able to replicate on all the following browsers; Arc, Brave, Safari, Firefox

### Version

All the browsers are running the latest stable version

**Comment by aapl-yumi** [comment]
The issue seems to be that there are two modals opening when pressing ⌘ + K. At the very bottom, of this screenshot, you can see that there is another layer of search modal open.
<img width="478" alt="Screenshot20230406111522@2x" src="https://user-images.githubusercontent.com/36561306/230423402-8acad7a6-71ec-47bd-9a22-266283380ff9.png">
Also, I noticed that when I type something in after pressing ⌘ + K, and close the modal in view, there is another search modal with whatever I typed in.

**Comment by aapl-yumi** [comment]
There seems to be two listeners listening for ⌘ + K
<img width="610" alt="Screenshot20230406113203@2x" src="https://user-images.githubusercontent.com/36561306/230427420-717021fc-0243-42f7-913f-eba4d5b09172.png">

**Comment by liamdebeasi** [comment]
This appears to be fixed after a recent update to Docusaurus.

**Comment by izyumidev** [comment]
Perfect! Thank you for letting me know!!
