### ISSUE TITLE
bug: scroll to the right button renders for short lists on playground

### ISSUE THREAD

**Issue by thetaPC** [ionic-team/ionic-docs#2999]
### Describe the Bug

The playground files will render a scroll to the right button when the the files view overflows (which makes sense):
![Screenshot 2023-06-15 at 1 12 50 PM](https://github.com/ionic-team/ionic-docs/assets/13530427/c60ff9a8-8e44-4145-8516-f0cbfef76c3c)

However, when I select a different framework that doesn't overflow, then the scroll to the right button still shows. This only happens when at least one framework has tabs that overflow.
![Screenshot 2023-06-15 at 1 19 02 PM](https://github.com/ionic-team/ionic-docs/assets/13530427/3828a846-c87e-4cc5-9a4e-9fe9e8d5c506)

### Expected Behavior

I expect to not see the scroll to the right button when the current tabs don't overflow.

![Screenshot 2023-06-15 at 1 18 38 PM](https://github.com/ionic-team/ionic-docs/assets/13530427/3882a3be-a016-4183-859c-f98beb668592)

### Steps to Reproduce

1. Navigate to the Action Sheet -> ["Collecting Role Information on Dismiss"](https://ionicframework.com/docs/api/action-sheet#collecting-role-information-on-dismiss) section
2. Verify that Angular is selected
3. Verify the scroll to the right button renders
4. Click on React
5. Notice the scroll to the right button is still present
6. Navigate to the Action Sheet -> ["Styling"](https://ionicframework.com/docs/api/action-sheet#collecting-role-information-on-dismiss)
7. Notice that the Angular doesn't render the scroll to the right button
8. Click on React
9. Notice the scroll to the right button is not rendered

### Screenshots

With bug:
Angular
![Screenshot 2023-06-15 at 1 12 50 PM](https://github.com/ionic-team/ionic-docs/assets/13530427/e04bcf59-e6ff-42d3-8633-c6e024cb8fc7)

React
![Screenshot 2023-06-15 at 1 19 02 PM](https://github.com/ionic-team/ionic-docs/assets/13530427/858091c9-82ab-4a3e-8bc3-f30425648f1c)

Without bug:
Angular
![Screenshot 2023-06-15 at 1 24 02 PM](https://github.com/ionic-team/ionic-docs/assets/13530427/9456ac06-ac0a-4d48-8e1c-30866c972eaa)

React
![Screenshot 2023-06-15 at 1 18 38 PM](https://github.com/ionic-team/ionic-docs/assets/13530427/68e13f1f-ac04-4276-b5b5-050d8d0b15c2)

### Operating System

macOS

### Browser

Firefox

### Version

114.0.1

### Additional Information

The code source can be found in the `PlaygrounTabs` [index](https://github.com/ionic-team/ionic-docs/blob/a0f9248167dc6125641b72dc0f519fb1d74657cb/src/components/global/PlaygroundTabs/index.tsx#L143-L166) file.

**Comment by amandaejohnston** [comment]
Thanks! I'm able to reproduce this. It looks like we need to re-update the `navVisible` states whenever the selected framework changes. (Theoretically, this should be as simple as adding `selectedValue` to the array passed into the `useEffect` [here](https://github.com/ionic-team/ionic-docs/blob/a0f9248167dc6125641b72dc0f519fb1d74657cb/src/components/global/PlaygroundTabs/index.tsx#LL108-L111).)

Right now, the scroll buttons are only updated on init and on scroll in the file list, so I suspect that whether they're set initially is dependent entirely on the Angular files, since Angular is the default. Thankfully, Angular generally has the most files, so we're less likely to have the opposite situation where you should be able to scroll but can't. That will change if we implement https://github.com/ionic-team/ionic-docs/issues/2798, though, so we should definitely fix this before then.

Side note: I actually didn't see the bug trigger on my first try, but every subsequent refresh (including incognito) did trigger it. Maybe I just clicked on React too fast the first time?

**Comment by thetaPC** [comment]
This will be available on the site soon!
