### ISSUE TITLE
bug: 

### ISSUE THREAD

**Issue by devlexus-Pavankumar** [ionic-team/ionic-docs#3048]
### Describe the Bug

unable to selecting month and date

### Expected Behavior

i want pick month and year what ever i want year and month

### Steps to Reproduce

dont know

### Screenshots

![Screenshot from 2023-07-18 18-59-40](https://github.com/ionic-team/ionic-docs/assets/133651829/bc51dc23-1c21-43c6-87c0-41751783fa73)

**Comment by amandaejohnston** [comment]
Thank you for the issue. It looks like you are describing an Ionic Framework issue, rather than a docs one. If this is the case, could you [open an issue over there](https://github.com/ionic-team/ionic-framework/issues/new/choose) instead? The template will help make sure we have all the information we need to triage the problem. Please also include steps to reproduce.

If this is for the docs, could you give more details, such as a link to the page in question?
