### ISSUE TITLE
feat: scroll y, toggle in list is not working

### ISSUE THREAD

**Issue by enricdema** [ionic-team/ionic-docs#3068]
### Describe Problem

scroll y, toggle in list is not working

### Describe Preferred Solution

ion-toggle{
  touch-action: auto!important;
}

**Comment by amandaejohnston** [comment]
Thank you for the report. It sounds like this is reporting a bug in Ionic Framework, rather than the docs. Please create a new issue over there instead, and include a runnable reproduction: https://github.com/ionic-team/ionic-framework/issues/new/choose The template on the Framework repo will help ensure we have all the details we need to triage the issue.
