### ISSUE TITLE
Picker options

### ISSUE THREAD

**Issue by wcmhc** [ionic-team/ionic-docs#499]
**URL**: (both are referenced in this issue)
* https://ionicframework.com/docs/api/datetime
* https://ionicframework.com/docs/api/picker

On the [DateTime & Picker docs](https://github.com/ionic-team/ionic/blob/82457d874ba006a634e48703dcfcde423d1b1230/core/src/components/picker-column/readme.md), there is a dead link at the `pickerOptions` subheading pointing to https://ionicframework.com/docs/picker/Picker. PR #347 says this is fixed but that link points to the v3 docs (which is a dead link anyway). 

I also can't seem to find usage docs for `ion-picker-column` for usage in `ion-picker-controller`'s `PickerColumn[]` property as it appears nowhere in the nav. I was able to find an [internal readme.md](https://github.com/ionic-team/ionic/blob/82457d874ba006a634e48703dcfcde423d1b1230/core/src/components/picker-column/readme.md), but this page doesn't explain anything useful.

Thank you!

**Comment by camwiegert** [comment]
@wcmhc Thanks for the feedback!

The `ion-picker-column` component isn't documented because it is for internal use only. And you're right that we don't properly document many of these types and interfaces like [`PickerColumn`](https://github.com/ionic-team/ionic/blob/master/core/src/components/picker/picker-interface.ts#L25-L39). I'm going to roll this into #229. Hope that helps until we have the types properly documented.
