### ISSUE TITLE
Please use same sample code as shown on demo!

### ISSUE THREAD

**Issue by iget-master** [ionic-team/ionic-docs#670]
**URL**
https://ionicframework.com/docs/api/card (and many others)

**What is missing or inaccurate about the content on this page?**

On many component documentation pages, the sample code is different of the demo shown on the right side of the page.

This is annoying because we see the demo and don't know how to implement it.
Maybe behind the demo we add a button "see source code".

**Comment by antoinecfmws** [comment]
Hello, 
I had a similar thought. Previously in Ionic3, we had the ability to scroll through the code and see the demo component to its right. Currently not all the code is matching with the demo. There's probably more code than demo. It would be great to have more examples rendered with their corresponding code. As an example ion-card (https://ionicframework.com/docs/api/card) has only one card in the docs, it would be nice to add multiple variation to showcase the beauty of these components.

**Comment by iget-master** [comment]
@rtpHarry do you guys care about improving Ionic documentation? I can see tons of issues here that anyone reads or reply.

**Comment by rtpHarry** [comment]
@iget-master I'm not actually on the Ionic team. I have contributed where I can. 

To be fair to the team, they have been working really hard from what I can see. They have gone from just Angular docs to building out a new v4 site and then also splitting it out to support React and Vue. 

You are correct that they don't seem to acknowledge much but I have opened a bunch of issues over time and then later on they have popped up as closed by a PR.

**Comment by dotNetkow** [comment]
Hi @iget-master - We do regularly make updates to the docs. Recent changes include updating them to Stencil One (for better performance among other things), the beginnings of supporting multiple app frameworks (React, Vue...), and yesterday: [linking to the sample code](https://github.com/ionic-team/ionic-docs/pull/792), like you're asking for. [Check it out](https://ionicframework.com/docs/api/card). :)

Like any open source project, there's always more of you (sometimes, literally millions) than us (a small company), so there will always be open issues. This is true regardless of company size: see [React](https://github.com/facebook/react) for example - 500+ issues open right now, even with the power of Facebook behind it.

We've got more docs changes planned, stay tuned. I'll keep this issue open because the solution deployed yesterday is likely not the final one.

Also, we do our best to acknowledge everyone as much as humanly possible. Thanks to @rtpHarry - we do see you and greatly appreciate your PRs! Cheers!

**Comment by brandyscarney** [comment]
Thanks for the issue! We have recently been migrating all of our API documentation over to include inline usage examples that can be opened in StackBlitz and played around with. I am going to close this as I think the playground examples completely solve this. We haven't finished migrating all of them but we are actively working on it. For more information on component playgrounds, check out this blog: https://ionic.io/blog/announcing-component-playgrounds-for-ionic-docs
