### ISSUE TITLE
Menu component: property options (overlay, reveal, etc.) need better descriptions

### ISSUE THREAD

**Issue by AndrWeisR** [ionic-team/ionic-docs#837]
**URL**
E.g. https://ionicframework.com/docs/api/menu

**What is missing or inaccurate about the content on this page?**
As a specific example, the doc states that the type property of ion-menu has available options: "overlay", "reveal", "push".
But nowhere does it describe what these options actually mean or do.

In general, the meaning of various property options is not well documented.

**Comment by brandyscarney** [comment]
Thanks for the issue! We have added some new playgrounds to the documentation which allows you to see and play with the components. You can also view the code in the different frameworks and copy it or open the example in StackBlitz. I'm going to close this because I think that this playground showing off the different types solves this, but let me know if not: https://ionicframework.com/docs/api/menu#menu-types
