### ISSUE TITLE
Android Studio - No support for ionic

### ISSUE THREAD

**Issue by josersleal** [ionic-team/ionic-docs#946]
**URL**
The URL at which the content is missing or inaccurate
https://ionicframework.com/docs/building/android

**What is missing or inaccurate about the content on this page?**
Android Studio is somehow necessary in order to be´ring the environment to build and run against the Android platform. However it does not support coding ionic without without cordova at all.
I suggest you should make a bigger effort to coordinate with IDE's in order to provide a better developer experience. At all levels.

Also  and maybe even more important is how in the days that go by, you forget to provide clear instructions on how to handle CI-CD from development, through automated QA into the stores.

This is an area where I believe you must improve and its long due.

let me know if I missed that information or know-how please

**Comment by dwieeb** [comment]
Maybe what's missing is a sentence like this:

> We don't advise using Android Studio for development, but it is required when building and running your app for the native Android platform.

Ionic is built primarily using web technologies and is cross-platform. Android Studio is only for building native Android apps. That's why we're building [Ionic Studio](https://ionicframework.com/studio). 

What would you find helpful in instructions for CI/CD that relates to Ionic, specifically? It would seem the majority of testing and building is relevant to the JS Framework and native layer you're using with Ionic, not Ionic specifically.

**Comment by josersleal** [comment]
Thats a good answer.
Concerning the CI, I think that the difficulties are mostly on IOS side due to limitations and complexity.
All and all we developers need to deal with 3 IDEs at least to build for the main mobile platforms. And the purpose of Ionic is to remove that obstacle. Together with say cordova..?
It's time you guys come up with an integrated solution. Maybe Ionic Studio? I don't know enough about it. Maybe integration to other services? Online devices for testing, build management and release. I am not adding names here but they are known.

**Comment by dwieeb** [comment]
In the end, Ionic apps are bundled in APK and IPA binaries just like native apps. The technology within the binaries differs, but Ionic apps must adhere to Play Store and App Store rules just like native apps. One of our goals is cross-platform, but that doesn't mean we're replacing the solutions offered by Google and Apple. [Capacitor](https://capacitor.ionicframework.com/) relies heavily on the dev using Android Studio and Xcode. We generally recommend the best tool for the job.

That being said, we're working on CI/CD for Ionic with [Appflow](https://ionicframework.com/appflow), especially Package, which builds binaries for Android and iOS. 

I guess in general, this stuff is hard. We're working on it. 😅

**Comment by Siedlerchr** [comment]
You only need Android Studio installed, because it installs the required Android sdk stuff and emulators, building works fine from command line. Regarding CI/CD. I have previously setup travis and now github actions to build an app for android (ios not yet, cause I am not yet having a a dev certificate)
